name: Build full (upstream)

on:
  push:
    branches:
      - full
    paths-ignore:
      - '*.md'

jobs:
  build-macos:
    name: build for macOS

    strategy:
      matrix:
        # macos-13 is x86_64, macos-14 is arm64
        os: [macos-13, macos-14]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 120

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: build ffmpeg
        run: |
          while sleep 300; do echo "=====[ $SECONDS seconds still running ]====="; done &
          VERBOSE=yes SKIPRAV1E=yes ./build-ffmpeg --build --enable-gpl-and-non-free
          kill %1
      - name: check shared library
        run: |
          otool -L ./workspace/bin/ffmpeg
      - name: test run ffmepg
        run: |
          ./workspace/bin/ffmpeg -buildconf

          - name: Rename binaries
          run: |
            mv workspace/bin/ffmpeg workspace/bin/ffmpeg-macos-${{ runner.arch }}
            mv workspace/bin/ffprobe workspace/bin/ffprobe-macos-${{ runner.arch }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: MacOS
          path: |
            workspace/bin/ffmpeg-macos-${{ runner.arch }}
            workspace/bin/ffprobe-macos-${{ runner.arch }}
  
      - name: clean up
        run: |
          ./build-ffmpeg --cleanup
