name: Build

on:
  push:
    tags:
      - '*'
    branches:
      - master
    paths-ignore:
      - '*.md'
  workflow_dispatch:

jobs:
  build-macos:
    name: build for macOS

    strategy:
      matrix:
        arch: [arm64, x86_64]
  
    runs-on: macos-latest
    timeout-minutes: 120

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install deps
        run: |
          arch -${{ matrix.arch }} brew install nasm yasm pkg-config cmake

# Useful for debugging:
#      - name: Setup tmate session
#        uses: mxschmitt/action-tmate@v3

      - run: |
          echo "${{ github.ref }}"

      - name: Build ffmpeg
        run: |
          while sleep 300; do echo "=====[ $SECONDS seconds still running ]====="; done &
          arch -${{ matrix.arch }} ./build-ffmpeg --build
          kill %1

      - name: Check shared library
        run: |
          arch -${{ matrix.arch }} otool -L ./workspace/bin/ffmpeg
          arch -${{ matrix.arch }} otool -L ./workspace/bin/ffprobe

      - name: Test run
        run: |
          arch -${{ matrix.arch }} ./workspace/bin/ffmpeg -buildconf
          arch -${{ matrix.arch }} ./workspace/bin/ffprobe -buildconf

      - name: Rename binaries
        run: |
          mv workspace/bin/ffmpeg workspace/bin/ffmpeg-macos-${{ matrix.arch }}
          mv workspace/bin/ffprobe workspace/bin/ffprobe-macos-${{ matrix.arch }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MacOS-${{ matrix.arch }}
          path: |
            workspace/bin/ffmpeg-macos-${{ matrix.arch }}
            workspace/bin/ffprobe-macos-${{ matrix.arch }}
  
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          files: |
            workspace/bin/ffmpeg-macos-${{ matrix.arch }}
            workspace/bin/ffprobe-macos-${{ matrix.arch }}
