name: Build

on:
  push:
    tags:
      - '*'
    branches:
      - master
    paths-ignore:
      - '*.md'
  workflow_dispatch:

jobs:
  build-macos:
    name: build for macOS

    strategy:
      matrix:
        runner: [macos-15, macos-15-intel]
  
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 120

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install deps
        run: |
          # dav1d needs meson and ninja along with nasm to be built
          brew install nasm yasm python-setuptools meson

# Useful for debugging:
#      - name: Setup tmate session
#        uses: mxschmitt/action-tmate@v3

      - run: |
          echo "${{ github.ref }}"

      - name: Build ffmpeg
        run: |
          while sleep 300; do echo "=====[ $SECONDS seconds still running ]====="; done &
          ./build-ffmpeg --build
          kill %1

      - name: Check shared library
        run: |
          otool -L ./workspace/bin/ffmpeg
          otool -L ./workspace/bin/ffprobe

      - name: Test run
        run: |
          ./workspace/bin/ffmpeg -buildconf
          ./workspace/bin/ffprobe -buildconf

      - name: Rename binaries
        run: |
          mv workspace/bin/ffmpeg workspace/bin/ffmpeg-macos-${{ runner.arch }}
          mv workspace/bin/ffprobe workspace/bin/ffprobe-macos-${{ runner.arch }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MacOS-${{ runner.arch }}
          path: |
            workspace/bin/ffmpeg-macos-${{ runner.arch }}
            workspace/bin/ffprobe-macos-${{ runner.arch }}
  
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          files: |
            workspace/bin/ffmpeg-macos-${{ runner.arch }}
            workspace/bin/ffprobe-macos-${{ runner.arch }}
